# ----------------------------------------
# 1. Configurações do Banco de Dados (MySQL)
# ----------------------------------------
# Substitua 'email_service_db' pelo nome que você criou no MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/email_service_db

# Usuário padrão do MySQL
spring.datasource.username=root

# Senha do MySQL (Usando variável de ambiente por segurança)
spring.datasource.password=1234

# Configurações do Driver e do Hibernate (Cria as tabelas sozinho)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ----------------------------------------
# 2. Configurações do RabbitMQ
# ----------------------------------------
broker.queue.email.name=default.email

# ----------------------------------------
# 3. Configurações de Envio de E-mail (Gmail)
# ----------------------------------------
spring.mail.host=smtp.gmail.com
spring.mail.port=587

# COLOQUE SEU EMAIL AQUI
spring.mail.username=seuemail@gmail.com

# COLOQUE SUA SENHA DE APLICATIVO DO GMAIL AQUI
spring.mail.password=SUA_SENHA_APP_AQUI

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true